// src/example/react-socket/src/tabs/CaptureTab/Views/NotSupported/NotSupported.tsx
import { Button } from '@fluentui/react-northstar'
import { Warning } from 'tabs/CaptureTab/Components'
import { useHistory } from 'react-router-dom'
import './NotSupported.scss'

export function NotSupported() {
  const history = useHistory()

  const tryAgainButtonHandler = () => {
    history.push('/capture')
  }

  return (
    <div className="not-supported-container">
      <Warning size="big">
        This device is unsupported due to a low camera frame rate. Please use this application on a different device.
      </Warning>

      <Button primary onClick={tryAgainButtonHandler} content="Back" />
    </div>
  )
}

// src/example/angular/src/app/views/not-supported/not-supported.component.ts
import { Component, OnInit } from '@angular/core'
import { Router } from '@angular/router'

@Component({
  selector: 'app-not-supported',
  templateUrl: './not-supported.component.html',
  styleUrls: ['./not-supported.component.scss'],
})

export class NotSupportedComponent implements OnInit {
  constructor(
    private router: Router,
  ) { }
  
  ngOnInit() {
  }

  async tryAgainButtonHandler() {
    this.router.navigate(['/'])
  }
}

<div class="not-supported-container">
  <app-warning size="big">
    This device is unsupported due to a low camera frame rate. Please use this application on a different device.
  </app-warning>

  <app-button (click)="tryAgainButtonHandler()" type="primary" size="small">Back</app-button>

  <app-footer></app-footer>

</div>
