// src/example/angular/src/app/components/info/info.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { MeasurementMeanData } from 'rppg/dist/lib/RPPGEvents.types'
import { translations } from 'src/consts/translations'
import { SCHEMA } from 'src/consts/'
@Component({
  selector: 'app-info',
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.scss'],
})

export class InfoComponent implements OnInit {
  @Input() processing!: boolean
  @Input() bgrData!: MeasurementMeanData
  @Input() lang!: string

  constructor() { }

  ngOnInit() {}


  get schema() {
    return SCHEMA.map(item => ({
      ...item,
      name: translations[this.lang][item.key],
    }))
  }

  trackById(index: number, item: any) {
    return item.key
}
}

<div class="info-container">
  <div class="info">
    <div class="data">
      <div *ngFor="let item of schema; trackBy: trackById" class="item">
        <div class="value">
          <div class="ring-calculating" *ngIf="!bgrData[item.key]">
            <img class="item-img" src='assets/images/{{item.icon}}'>
            <span></span>
          </div>
          <div class="ring-calculated" *ngIf="bgrData[item.key]">
            <img class="item-img" src='assets/images/result-mark.svg'>
          </div>
        </div>
        <div class="name">
          {{item.name}}
        </div>
      </div>
    </div>
  </div>
</div>

// src/example/react/src/tabs/CaptureTab/Components/Info/Info.tsx
import React from 'react'
import { getSchema } from 'helpers/capture'
import { RPPGData } from 'helpers/rppg'
import { get } from 'lodash'
import './Info.scss'

type Props = {
 rppgData: RPPGData
}

export const Info: React.FC<Props> = ({rppgData}) => {
  const schema = getSchema()

  return (
    <div className="info-container">
      <div className="info">
        <div className="data">
          {schema?.map(item => (
            <div
              className="item"
              key={item.key}
            >
              <div className="value">
                {get(rppgData, item.key, 0) ? (
                  <div className="ring-calculated">
                    <img
                      className="item-img"
                      src={require('assets/images/result-mark.svg').default}
                      alt="calculated"
                    />
                  </div>
                ) : (
                  <div className="ring-calculating">
                    <img
                      className="item-img"
                      src={require(`assets/images/${item.icon}`).default}
                      alt="calculating"/>
                    <span></span>
                  </div>
                )}
              </div>
              <div className="name">
                {item.name}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
