// src/example/react-socket/src/tabs/CaptureTab/Components/Warning/Warning.tsx
import './Warning.scss'

type Props = {
  size: string
}

export const Warning: React.FC<Props> = ({
  children,
  size,
}) => {
  return (
    <div className={`warning-container ${size}`}>
      <img
        className="warning-image"
        src={require('assets/images/warning.svg').default}
        alt="Warning"
      />
      <p className="warning-message">
        {children}
      </p>
    </div>
  )
}

// src/example/angular/src/app/components/warning/warning.component.ts
import { Component, Input, OnInit } from '@angular/core'

@Component({
  selector: 'app-warning',
  templateUrl: './warning.component.html',
  styleUrls: ['./warning.component.scss'],
})

export class WarningComponent implements OnInit{
  @Input() size = 'normal'
  @Input() message: string

  constructor() { }

  ngOnInit() { }
}

<div class="warning-container" [ngClass]="size" >
  <img class="warning-image" src="assets/images/warning.svg">
  <p class="warning-message">
    <ng-content></ng-content>
  </p>
</div>
