// src/example/react-socket/src/tabs/CaptureTab/Views/BadConditions/BadConditions.tsx
import { Button } from '@fluentui/react-northstar'
import { useHistory } from 'react-router-dom'
import './BadConditions.scss'

export function BadConditions() {
  const history = useHistory()

  const tryAgainButtonHandler = () => {
    history.push('/capture')
  }

  return (
    <div className="bad-conditions-container">
      <div className="title-error">Error</div>
      <div className="message-container">
        <div className="title">Unable to take readings</div>
        <div className="content">
          This error can occur if there was too much movement in
          the camera frame or if the lighting conditions were unstable.
          Please try again in more stable conditions and ensure your face is evenly lit.
        </div>
      </div>

      <Button onClick={tryAgainButtonHandler} primary content="Try Again" />

    </div>
  )
}

// src/example/angular/src/app/views/bad-conditions/bad-conditions.component.ts
import { Component, OnInit } from '@angular/core'
import { Router } from '@angular/router'

@Component({
  selector: 'app-bad-conditions',
  templateUrl: './bad-conditions.component.html',
  styleUrls: ['./bad-conditions.component.scss'],
})

export class BadConditionsComponent implements OnInit {
  constructor(
    private router: Router,
  ) { }
  
  ngOnInit() {
  }

  async tryAgainButtonHandler() {
    this.router.navigate(['/measurement'])
  }
}

<div class="bad-conditions-container">
  <app-warning size="big">
    We’re unable to take readings due to bad lighting conditions. Please try again and ensure your face is well lit.
  </app-warning>

  <app-button (click)="tryAgainButtonHandler()" type="primary" size="small">Try Again</app-button>

  <app-footer></app-footer>

</div>
