// src/example/react-socket/src/helpers/loadingScreen.ts
import { CSSProperties } from 'react'

export const loadingScreenMessages = [
  'We\'re loading an awesome module onto your device...',
  'Using this, your web browser will turn into a remote monitoring tool...',
  'Using AI, we will be able to understand your physiology...',
  'Please wait. This won\'t take long...',
]

export const loadingScreenDelay = 8000

export const spinnerCssOverride: CSSProperties = {
  borderWidth: '4px',
  borderColor: 'rgba(255, 255, 255, 0.7) rgba(255, 255, 255, 0.7) rgba(255, 255, 255, 0.063)',
}

export const spinnerSpeedMultiplier = 0.75

export const spinnerSize = 64

// src/example/angular/src/app/components/loading-screen/loading-screen.component.ts
import { Component, OnInit } from '@angular/core'
import { NgxSpinnerService } from "ngx-spinner"

@Component({
  selector: 'app-loading-screen',
  templateUrl: './loading-screen.component.html',
  styleUrls: ['./loading-screen.component.scss'],
})

export class LoadingScreenComponent implements OnInit {
  messages = [
    'We’re loading an awesome module onto your device...',
    'Using this, your web browser will turn into a remote monitoring tool...',
    'Using AI, we will be able to understand your physiology...',
    'Please wait. This won’t take long...',
  ]
  step = 0
  delay = 8000
  interval = null

  constructor(
    private spinner: NgxSpinnerService,
  ) { }

  get message() {
    return this.messages[this.step]
  }
  
  ngOnInit() {
    this.spinner.show()
    this.interval = setInterval(() => {
      this.step++
      if (this.step >= this.messages.length) {
        this.step = 0
      }
    }, this.delay)
  }
}

<div class="loading-screen-container">
  <div class="spinner-wrapper">
    <ngx-spinner
      [fullScreen]="false"
      bdColor="rgba(0,0,0,0.3)"
      size="medium"
      type="ball-clip-rotate"
      >
    </ngx-spinner>
  </div>
  <div class="message-wrapper">
    {{message}}
  </div>
</div>
